#!/bin/bash -ex
# Rebuildthe example using the latest code.
# Copyright (C) 2023  Kevin Sandom

mkdir -p examples/example1
cd examples/example1
rm -Rf cvData/{src,compiled}
cvGenerateBase --force

cp -v ../variant/* cvData/variant
cp -v ../template.md cvData/

customJob="CompanyC-Job1"
cvNew "$customJob"
cv "$customJob"

cv

if which dolphin; then
    dolphin . &
fi
