#!/bin/bash -ex
# Rebuildthe example using the latest code.

cd examples
rm -Rf cvData/{src,compiled}
cvGenerateBase --force

cp -v variant/* cvData/variant

cv

if which dolphin; then
    dolphin . &
fi
